/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        hotel: {
          primary: "#D4AF37",
          secondary: "#1F2937",
          accent: "#F3F4F6",
          dark: "#111827",
          gold: "#FFD700",
          darkGold: "#B8860B",
        }
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.25rem' }],
        'base': ['1rem', { lineHeight: '1.5rem' }],
        'lg': ['1.125rem', { lineHeight: '1.75rem' }],
        'xl': ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '1' }],
        '9xl': ['8rem', { lineHeight: '1' }],
        // Enhanced hotel sizes with better spacing
        'hotel-xs': ['0.7rem', { lineHeight: '0.9rem', letterSpacing: '0.01em' }],
        'hotel-sm': ['0.85rem', { lineHeight: '1.1rem', letterSpacing: '0.01em' }],
        'hotel-base': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.005em' }],
        'hotel-lg': ['1.15rem', { lineHeight: '1.65rem', letterSpacing: '0.005em' }],
        'hotel-xl': ['1.35rem', { lineHeight: '1.85rem', letterSpacing: '0.01em' }],
        'hotel-2xl': ['1.65rem', { lineHeight: '2.1rem', letterSpacing: '0.01em' }],
        'hotel-3xl': ['2.1rem', { lineHeight: '2.5rem', letterSpacing: '0.015em' }],
        'hotel-4xl': ['2.6rem', { lineHeight: '3.1rem', letterSpacing: '0.02em' }],
        'hotel-5xl': ['3.6rem', { lineHeight: '4.2rem', letterSpacing: '0.025em' }],
        'hotel-hero': ['4.2rem', { lineHeight: '4.8rem', letterSpacing: '0.03em' }],
        'hotel-display': ['5.2rem', { lineHeight: '5.8rem', letterSpacing: '0.035em' }],
        // Additional specialized sizes
        'hotel-caption': ['0.65rem', { lineHeight: '0.85rem', letterSpacing: '0.02em' }],
        'hotel-tiny': ['0.8rem', { lineHeight: '1rem', letterSpacing: '0.01em' }],
        'hotel-medium': ['1.05rem', { lineHeight: '1.55rem', letterSpacing: '0.005em' }],
        'hotel-large': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0.01em' }],
        'hotel-huge': ['1.85rem', { lineHeight: '2.2rem', letterSpacing: '0.015em' }],
        'hotel-massive': ['2.4rem', { lineHeight: '2.8rem', letterSpacing: '0.02em' }],
        'hotel-gigantic': ['3.2rem', { lineHeight: '3.7rem', letterSpacing: '0.025em' }],
      },
      fontWeight: {
        'thin': '100',
        'extralight': '200',
        'light': '300',
        'normal': '400',
        'medium': '500',
        'semibold': '600',
        'bold': '700',
        'extrabold': '800',
        'black': '900',
        // Enhanced hotel weights with more precision
        'hotel-thin': '200',
        'hotel-light': '300',
        'hotel-regular': '400',
        'hotel-normal': '450',
        'hotel-medium': '500',
        'hotel-strong': '550',
        'hotel-semibold': '600',
        'hotel-bold': '700',
        'hotel-heavy': '750',
        'hotel-black': '800',
        'hotel-ultra': '900',
      },
      fontFamily: {
        'sans': ['Jost', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'serif': ['Gilda Display', 'ui-serif', 'Georgia', 'serif'],
        'mono': ['ui-monospace', 'SFMono-Regular', 'monospace'],
        // Hotel specific fonts enhanced
        'hotel-primary': ['Jost', 'Inter', 'sans-serif'],
        'hotel-display': ['Gilda Display', 'Playfair Display', 'serif'],
        'hotel-elegant': ['Playfair Display', 'Crimson Text', 'serif'],
        'hotel-modern': ['Inter', 'Roboto', 'sans-serif'],
        'hotel-luxury': ['Cormorant Garamond', 'Libre Baskerville', 'serif'],
      },
      letterSpacing: {
        'tighter': '-0.05em',
        'tight': '-0.025em',
        'normal': '0em',
        'wide': '0.025em',
        'wider': '0.05em',
        'widest': '0.1em',
        // Enhanced hotel specific spacing
        'hotel-tightest': '-0.03em',
        'hotel-tight': '-0.02em',
        'hotel-snug': '-0.01em',
        'hotel-normal': '0em',
        'hotel-relaxed': '0.01em',
        'hotel-wide': '0.02em',
        'hotel-wider': '0.03em',
        'hotel-luxury': '0.1em',
        'hotel-elegant': '0.15em',
        'hotel-spacious': '0.2em',
      },
      lineHeight: {
        'none': '1',
        'tight': '1.25',
        'snug': '1.375',
        'normal': '1.5',
        'relaxed': '1.625',
        'loose': '2',
        // Hotel specific line heights
        'hotel-tight': '1.2',
        'hotel-snug': '1.3',
        'hotel-normal': '1.4',
        'hotel-relaxed': '1.6',
        'hotel-loose': '1.8',
        'hotel-spacious': '2.0',
        'hotel-airy': '2.2',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
